#!/bin/bash

# 2 Bytes, first 13 bits are buttons then 3 padding bits
# 1 byte 4  bits HAT (includes diagonal directions, 4 bits padding
# 4 bytes X Y Z RZ. analoge 0-255
# 12 bytes "Vendor defined" INPUT
# 8 bytes - Feature

#8 bytes INPUT (4 X 0-1023)

# Create xac_joystick gadget
cd /sys/kernel/config/usb_gadget/
mkdir -p xac_joystick
cd xac_joystick

# Define USB specification
echo 0x11C0 > idVendor # ACRUX
echo 0x5503  > idProduct # Multifunction Composite Joystick Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0x00 > bDeviceClass
echo 0x00 > bDeviceSubClass
echo 0x00 > bDeviceProtocol

# Perform localization
mkdir -p strings/0x409


echo "DEADCAFE" > strings/0x409/serialnumber
echo "Raspberry Pi" > strings/0x409/manufacturer
echo "VGame Controller" > strings/0x409/product


# Define the functions of the device
mkdir functions/hid.usb0
echo 0 > functions/hid.usb0/protocol
echo 0 > functions/hid.usb0/subclass
echo 7 > functions/hid.usb0/report_length

# PS3 Style Controller
# Read from the original device using mac-hid-dump

echo "05010905a10115002501350045017501950d05091901290d81029503810105012507463b017504950165140939814265009501810126ff0046ff000930093109320935750895048102c0" | xxd -r -ps > functions/hid.usb0/report_desc


# Create configuration file
mkdir configs/c.1
mkdir configs/c.1/strings/0x409

echo 0x80 > configs/c.1/bmAttributes
echo 100 > configs/c.1/MaxPower # 100 mA
echo "Wheel" > configs/c.1/strings/0x409/configuration

# Link the configuration file
ln -s functions/hid.usb0 configs/c.1

# Activate device 
ls /sys/class/udc > UDC

sleep 10
