#!/bin/bash
# Created by https://github.com/milador/XAC-Virtual-Joystick
#sleep 10

# Create xac_joystick gadget
cd /sys/kernel/config/usb_gadget/
mkdir -p xac_joystick
cd xac_joystick

# Define USB specification
echo 0x046d > idVendor # Logitech
echo 0xc294 > idProduct # Driging force GT
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0x00 > bDeviceClass
echo 0x00 > bDeviceSubClass
echo 0x00 > bDeviceProtocol

# Perform localization
mkdir -p strings/0x409

echo "12341234" > strings/0x409/serialnumber
echo "Logitech, Inc." > strings/0x409/manufacturer
echo "Driving Force GT" > strings/0x409/product


# Define the functions of the device
mkdir functions/hid.usb0
echo 0 > functions/hid.usb0/protocol
echo 0 > functions/hid.usb0/subclass
echo 7 > functions/hid.usb0/report_length

# Logitech Driving Force GT
# Read from the original device using mac-hid-dump

echo "05010904a101a1029501750a150026ff03350046ff0309308102950c75012501450105091901290c810295020600ff090181020501093126ff0046ff009501750881022507463b0175046514093981427501950465000600ff09012501450181029502750826ff0046ff0009028102c0a10226ff0046ff009507750809039102c0c0"| xxd -r -ps > functions/hid.usb0/report_desc


# Create configuration file
mkdir configs/c.1
mkdir configs/c.1/strings/0x409

echo 0x80 > configs/c.1/bmAttributes
echo 100 > configs/c.1/MaxPower # 100 mA
echo "Wheel" > configs/c.1/strings/0x409/configuration

# Link the configuration file
ln -s functions/hid.usb0 configs/c.1

# Activate device 
ls /sys/class/udc > UDC

sleep 10
